### ISSUE TITLE
Solution to an error in the 1st commit lab 03

### ISSUE THREAD

**Issue by Laiaborrell** [Albert-Alvarez/masb#11]
When running the first part of the code in arduino the following error appears:
`no matching function for call to 'HardwareTimer::attachInterrupt(void (&)(HardwareTimer*))`
If you remove the  "HardwareTimer*" argument when defining the ISR function (`cambiarEstadoLED`) this error will no longer appear.

**Comment by AdriaDiaz** [comment]
Thanks!
