### ISSUE TITLE
Connection between host and slave

### ISSUE THREAD

**Issue by HelenaRD33** [Albert-Alvarez/masb#32]
Hi Albert!

From the workflows available in the README, what I understand is that when we start the measurement in the ViSens it has to start the communication with the micro to obtain the data of the CV or CA. However, I don't understand if this communication has to be established directly in the main.c or via the app.  

Thank you in advance.

**Comment by Albert-Alvarez** [comment]
The app only sends measurement requests (CA or CV). It's the microcontroller who sends the measured data to the app automatically (each time a sample is taken) until the measurement is finished.
