### ISSUE TITLE
Structure and extension of the reports

### ISSUE THREAD

**Issue by HelenaRD33** [Albert-Alvarez/masb#5]
Hello Albert,

When writting the reports for the sessions, should we follow the points given in the README "entregables" and keep them short and concise or should we also add the typical structure (Introduction, methods, results, conclusions, etc.) and have a larger, more elaborated extension?

Thank you in advance,

Helena

**Comment by Albert-Alvarez** [comment]
Answered on [https://campusvirtual.ub.edu/mod/forum/discuss.php?d=245198](https://campusvirtual.ub.edu/mod/forum/discuss.php?d=245198).
